version: "3.4"

services:

  web:
    image: angelcam/developer-docs:latest
    hostname: '{{ index .Service.Labels "com.angelcam.name" }}-{{ index .Service.Labels "com.angelcam.env" }}-{{ .Node.Hostname }}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        com.angelcam.name: developer-docs
        com.angelcam.env: swarm-test
      resources:
        limits:
          memory: 500M
    ports:
      - 8012:3123
